'use strict';
const KEY='betterday-test-mvp-v2';
const ids=['sleepHours','sleepQuality','mood','hrv','hrvBase','rhr','rhrBase','moveMinutes','moveIntensity'];
const $=id=>document.getElementById(id);
const dateKey=()=>new Date().toISOString().slice(0,10);
function getAll(){let a={days:{}};try{a=JSON.parse(localStorage.getItem(KEY)||'{"days":{}}')}catch(e){};if(!a.days)a.days={};if(!a.days[dateKey()])a.days[dateKey()]={meals:[],water:0,waterTarget:2000};return a}
function putAll(a){localStorage.setItem(KEY,JSON.stringify(a))}
function clamp(x,a,b){return Math.max(a,Math.min(b,x))}
function foodScore(d){if(!d.meals?.length)return null;const avg=d.meals.reduce((s,m)=>s+Number(m.nova4||0),0)/d.meals.length;const good=100-avg;if(good===100)return 10;return clamp(Math.floor(good/10),0,9)}
function sleepScore(d){if(!d.sleepHours)return null;const h=Number(d.sleepHours);let dur=h>=7&&h<=9?10:h>=6.5&&h<7?8:h>9&&h<=10?8:h>=6&&h<6.5?6:h>10?6:h>=5?4:2;const q=Number(d.sleepQuality||6);return Math.round((dur*.75+q*.25)*10)/10}
function moveScore(d){const m=Number(d.moveMinutes||0);if(!d.moveMinutes&&d.moveMinutes!==0)return null;if(m===0)return 3;return clamp(m>=90?10:m>=60?9:m>=45?8:m>=30?7:m>=20?6:5,0,10)}
function waterScore(d){const t=Number(d.waterTarget||2000);return clamp(Math.floor((Number(d.water||0)/t)*10),0,10)}
function recovery(d){let sig=0,neg=0,pos=0,r=[];if(d.hrv&&d.hrvBase){sig++;const q=+d.hrv/+d.hrvBase;if(q<.9){neg++;r.push('HRV trend is below your recent baseline')}else if(q>1.05){pos++;r.push('HRV is above your recent baseline')}else r.push('HRV is around your recent baseline')}if(d.rhr&&d.rhrBase){sig++;const x=+d.rhr-+d.rhrBase;if(x>=5){neg++;r.push('resting heart rate is higher than usual')}else if(x<=-3){pos++;r.push('resting heart rate is lower than usual')}else r.push('resting heart rate is around usual')}if(d.mood){sig++;if(+d.mood<=4){neg++;r.push('you reported feeling low')}else if(+d.mood>=8){pos++;r.push('you reported feeling good')}else r.push('your morning wellbeing is around the middle of your range')}const s=sleepScore(d);if(s!==null){sig++;if(s<6){neg++;r.push('sleep was below range')}else if(s>=8){pos++;r.push('sleep was strong')}}return{state:sig<2?'Not enough data':neg>=2?'Below normal':pos>=2&&neg===0?'Well recovered':'Normal',reasons:r}}
function lifestyle(d){const vals=[foodScore(d),moveScore(d),sleepScore(d),waterScore(d)].filter(v=>v!==null);return vals.length<2?null:Math.round(vals.reduce((a,b)=>a+b,0)/vals.length*10)}
function balance(d){const vals=[foodScore(d),moveScore(d),sleepScore(d),waterScore(d)].filter(v=>v!==null);if(vals.length<3)return'Building picture';const spread=Math.max(...vals)-Math.min(...vals);return spread<=2?'Good balance':spread<=4?'Some imbalance':'Needs attention'}
function recommendation(d){const r=recovery(d);if(!d.sleepHours&&!d.mood)return['Start with a quick check-in','Add sleep and mood so BetterDay can give you a useful recommendation.'];if(r.state==='Below normal')return['Take a little pressure off','Your recovery signals are lower than usual. Keep movement easier, hydrate well and aim for mostly minimally processed meals.'];const scores=[['food',foodScore(d)],['movement',moveScore(d)],['sleep',sleepScore(d)],['hydration',waterScore(d)]].filter(x=>x[1]!==null).sort((a,b)=>a[1]-b[1]);if(!scores.length)return['Keep it simple','Build the picture with a few useful entries today.'];return scores[0][0]==='sleep'?['Protect your sleep','Sleep is currently the weakest part of the picture.']:scores[0][0]==='hydration'?['Catch up on hydration','Hydration is lagging today. A few simple drinks may be the most useful improvement.']:scores[0][0]==='food'?['Make the next meal count','Aim for a mostly minimally processed next meal rather than trying to fix the whole day.']:['Get some movement in','A walk or purposeful activity would help round out your day.']}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');window.scrollTo(0,0);render()}
function render(){const a=getAll(),d=a.days[dateKey()];$('dateLabel').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'});const l=lifestyle(d);$('lifestyleScore').textContent=l??'—';$('balanceLabel').textContent=balance(d);const rec=recommendation(d);$('focusTitle').textContent=rec[0];$('focusText').textContent=rec[1];const f=foodScore(d),m=moveScore(d),s=sleepScore(d),w=waterScore(d);$('foodMini').textContent=f===null?'—':f+'/10';$('moveMini').textContent=m===null?'—':m+'/10';$('sleepMini').textContent=s===null?'—':s+'/10';$('waterMini').textContent=w+'/10';const rr=recovery(d);$('recoveryState').textContent=rr.state;$('recoveryWhy').textContent=rr.reasons.join('; ')||'Add mood, sleep or wearable data to build the picture.';$('recoveryDetail').textContent=(rr.reasons.join('; ')||'No recovery trend yet.')+' BetterDay treats HRV as a personal trend, not a population target.';$('waterTotal').textContent=(d.water||0)+' ml';$('waterTarget').value=d.waterTarget||2000;ids.forEach(id=>{if($(id))$(id).value=d[id]??''});$('mealList').innerHTML=d.meals?.length?d.meals.map(x=>`<div class="meal"><span>${escapeHtml(x.text)}</span><b>${100-x.nova4}% N1–3</b></div>`).join(''):'No meals logged yet.';$('whyScore').innerHTML=`Food <b>${f??'—'}/10</b><br>Movement <b>${m??'—'}/10</b><br>Sleep <b>${s??'—'}/10</b><br>Hydration <b>${w}/10</b><br><br>Lifestyle is the average of available behaviour pillars. Recovery changes guidance rather than directly changing the score.`;renderWeek(a)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderWeek(a){const rows=Object.keys(a.days).sort().slice(-7).map(k=>a.days[k]);const scores=rows.map(lifestyle).filter(x=>x!==null);if(!scores.length)return;$ ('weeklyAvg').textContent=Math.round(scores.reduce((a,b)=>a+b,0)/scores.length);const av=fn=>{const v=rows.map(fn).filter(x=>x!==null);return v.length?(v.reduce((a,b)=>a+b,0)/v.length).toFixed(1):'—'};const stats={Food:av(foodScore),Movement:av(moveScore),Sleep:av(sleepScore),Hydration:av(waterScore)};$('weeklyStats').innerHTML=Object.entries(stats).map(([k,v])=>`${k}: <b>${v}</b><br>`).join('');const arr=Object.entries(stats).filter(x=>x[1]!=='—').sort((a,b)=>+a[1]-+b[1]);if(arr.length){$('weeklyFocus').textContent='Focus on '+arr[0][0].toLowerCase();$('weeklyFocusText').textContent=arr[0][0]+' is the lowest scoring part of your recent week. Improve it gently without neglecting the other areas.'}}
window.addEventListener('DOMContentLoaded',()=>{const st=$('appStatus');st.textContent='App connected ✓';st.classList.remove('bad');st.classList.add('good');document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.go)));document.querySelectorAll('[data-water]').forEach(b=>b.addEventListener('click',()=>{const a=getAll(),d=a.days[dateKey()];d.water=Number(d.water||0)+Number(b.dataset.water);putAll(a);render()}));$('nova4Range').addEventListener('input',e=>$('nova4Label').textContent=e.target.value+'%');$('waterTarget').addEventListener('change',e=>{const a=getAll();a.days[dateKey()].waterTarget=Number(e.target.value||2000);putAll(a);render()});$('checkinForm').addEventListener('submit',e=>{e.preventDefault();const a=getAll(),d=a.days[dateKey()];ids.forEach(id=>d[id]=$(id).value);putAll(a);show('today')});$('mealForm').addEventListener('submit',e=>{e.preventDefault();const text=$('mealText').value.trim();if(!text){alert('Describe the meal first.');return}const a=getAll(),d=a.days[dateKey()];d.meals=d.meals||[];d.meals.push({text,nova4:Number($('nova4Range').value)});putAll(a);$('mealText').value='';$('nova4Range').value=0;$('nova4Label').textContent='0%';render()});$('resetButton').addEventListener('click',()=>{if(confirm('Reset all prototype data?')){localStorage.removeItem(KEY);location.reload()}});render()});
